### ISSUE TITLE
Document the difference to pure QML

### ISSUE THREAD

**Issue by ShalokShalom** [BrigJS/brig#7]
QML is indeed Javascript and you can write in pure JS in each QML file 

Where is the difference to this project?

**Comment by cfsghost** [comment]
The JavaScript in QML is limited, which is used for QML components control only. If you need more functions that something's like system calls(FileSystem, Socket, crypto ...etc) or using external libraries, C/C++ is the only way to make it.

`Brig` project provides a way to make it possible to use Node.js to extends QML without C/C++, that means you can do more thing in QML with NPM modules and Node.js APIs.

**Comment by ShalokShalom** [comment]
Aha, so it basically expands the JS compatibility to Qt with Node.js? You may want to add that information on the README and so. Thanks a lot for the clarification, I will add that to the bindings section of the Qt Wiki, once an internal issue is solved.
